Repository umccr/pyriandx, pull requests merged in 2022-08, with the labels that each got.

#10 Allow for authentication token
  pyriandx/client.py
Labels: enhancement

#11 Release 0.3.0rc1
  .github/workflows/prbuild.yml
  .pre-commit-config.yaml
  .secrets.baseline
  CHANGELOG.rst
  LICENSE
  Makefile
  README.md
  docs/.buildinfo
  docs/coverage/status.json
  pyproject.toml
  pyriandx/__init__.py
  pyriandx/utils.py
  setup.cfg
  setup.py
  tests/test_cli.py
  tox.ini
Labels: enhancement

#12 Allowed request_data parameter overload
  pyriandx/client.py
Labels: enhancement

#14 Release 0.3.0 docs
  docs/_sources/user.rst.txt
  docs/_static/_sphinx_javascript_frameworks_compat.js
  docs/_static/basic.css
  docs/_static/doctools.js
  docs/_static/documentation_options.js
  docs/_static/jquery-3.6.0.js
  docs/_static/jquery.js
  docs/_static/language_data.js
  docs/_static/pygments.css
  docs/_static/searchtools.js
  docs/_static/underscore-1.13.1.js
  docs/_static/underscore.js
  docs/changelog.html
  docs/coverage/coverage_html.js
  docs/coverage/d_10afcb99a7eb7404___init___py.html
  docs/coverage/d_10afcb99a7eb7404___main___py.html
  docs/coverage/d_10afcb99a7eb7404_cli_py.html
  docs/coverage/d_10afcb99a7eb7404_client_py.html
  docs/coverage/d_10afcb99a7eb7404_utils_py.html
  docs/coverage/favicon_32.png
  docs/coverage/index.html
  docs/coverage/keybd_closed.png
  docs/coverage/keybd_open.png
  docs/coverage/style.css
  docs/developer.html
  docs/genindex.html
  docs/index.html
  docs/main.html
  docs/pyriandx/cli.html
  docs/pyriandx/client.html
  docs/pyriandx/index.html
  docs/pyriandx/utils.html
  docs/search.html
  docs/searchindex.js
  docs/user.html
Labels: documentation

#15 Update README
  README.md
Labels: documentation

#19 Bump version to 0.4.0
  pyriandx/__init__.py
Labels: general availability
